language: python

python:
  - 3.6

services:
  - postgresql

env:
  - DJANGO=2.0 DB=postgresql

before_install:
  - export DJANGO_SETTINGS_MODULE=skill_finder.settings

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE skill_finder;" -U postgres
  - psql -c "CREATE USER root WITH PASSWORD 'pass@123';" -U postgres
  - psql -c "ALTER USER root CREATEDB;" -U postgres
  - python3 manage.py makemigrations
  - python3 manage.py migrate

script:
  - flake8
  - python3 manage.py test
  